export default [
  {
    id: "1",
    title: "Задание 1: XSS",
    vulnerability: "XSS",
    description: "Сохранение XSS в HTML-контексте без кодирования",
    path: "/vulnerable-app/xss.html",
    language: "html",
  },
  {
    id: "2",
    title: "Задание 2: XSS",
    vulnerability: "XSS",
    description: "Сохранение XSS в HTML-контексте без кодирования",
    path: "/vulnerable-app/xss.html",
    language: "html",
  },
  {
    id: "3",
    title: "Задание 3: XSS",
    vulnerability: "XSS",
    description: "Сохранение XSS в HTML-контексте без кодирования",
    path: "/vulnerable-app/xss.html",
    language: "html",
  },
  {
    id: "4",
    title: "Задание 2: CSRF",
    vulnerability: "CSRF",
    description: "CSRF, где проверка токена зависит от наличия токена",
    path: "/vulnerable-app/csrf.html",
    language: "javascript",
  },
  {
    id: "5",
    title: "Задание 2: Пупупу",
    vulnerability: "CSRF",
    description: "Вот такие пироги",
    path: "/vulnerable-app/csrf.html",
    language: "javascript",
  },
  {
    id: "6",
    title: "Задание 3: Анекдот",
    vulnerability: "CSRF",
    description: "Анекдот про пилу",
    path: "vulnerable-app/anecdot.html",
    language: "javascript",
  },
  {
    id: "7",
    title: "Задание 4: Анекдот 2",
    vulnerability: "CSRF",
    description: "Анекдот 'Хипуешь, плесень'",
    path: "/vulnerable-app/csrf.html",
    language: "javascript",
  },
]
